/**
 * app.bkper.com
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AccountBalances } from './accountBalances';
import { GroupBalances } from './groupBalances';

export class Balances {
    'accountBalances'?: Array<AccountBalances>;
    'balanceCheckedType'?: Balances.BalanceCheckedType;
    'groupBalances'?: Array<GroupBalances>;
    'nextRange'?: string;
    'periodicity'?: Balances.Periodicity;
    'previousRange'?: string;
    'range'?: string;
    'totalRemovedBalances'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "accountBalances",
            "baseName": "accountBalances",
            "type": "Array<AccountBalances>"
        },
        {
            "name": "balanceCheckedType",
            "baseName": "balanceCheckedType",
            "type": "Balances.BalanceCheckedType"
        },
        {
            "name": "groupBalances",
            "baseName": "groupBalances",
            "type": "Array<GroupBalances>"
        },
        {
            "name": "nextRange",
            "baseName": "nextRange",
            "type": "string"
        },
        {
            "name": "periodicity",
            "baseName": "periodicity",
            "type": "Balances.Periodicity"
        },
        {
            "name": "previousRange",
            "baseName": "previousRange",
            "type": "string"
        },
        {
            "name": "range",
            "baseName": "range",
            "type": "string"
        },
        {
            "name": "totalRemovedBalances",
            "baseName": "totalRemovedBalances",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Balances.attributeTypeMap;
    }
}

export namespace Balances {
    export enum BalanceCheckedType {
        FullBalance = <any> 'FULL_BALANCE',
        CheckedBalance = <any> 'CHECKED_BALANCE',
        UncheckedBalance = <any> 'UNCHECKED_BALANCE'
    }
    export enum Periodicity {
        Daily = <any> 'DAILY',
        Monthly = <any> 'MONTHLY',
        Yearly = <any> 'YEARLY'
    }
}
