/**
 * app.bkper.com
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Book } from './book';

export class Collection {
    /**
    * The id of agent that created the resource
    */
    'agentId'?: string;
    /**
    * The Books contained in the Collection
    */
    'books'?: Array<Book>;
    /**
    * The creation timestamp, in milliseconds
    */
    'createdAt'?: string;
    /**
    * The unique id of the Collection
    */
    'id'?: string;
    /**
    * The name of the Collection
    */
    'name'?: string;
    /**
    * The username of the Collection owner
    */
    'ownerUsername'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "agentId",
            "baseName": "agentId",
            "type": "string"
        },
        {
            "name": "books",
            "baseName": "books",
            "type": "Array<Book>"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "ownerUsername",
            "baseName": "ownerUsername",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Collection.attributeTypeMap;
    }
}

