/**
 * app.bkper.com
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Event } from './event';

export class EventList {
    /**
    * The cursor, for pagination
    */
    'cursor'?: string;
    /**
    * List items
    */
    'items'?: Array<Event>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "cursor",
            "baseName": "cursor",
            "type": "string"
        },
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<Event>"
        }    ];

    static getAttributeTypeMap() {
        return EventList.attributeTypeMap;
    }
}

