/**
 * app.bkper.com
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class Group {
    /**
    * The id of agent that created the resource
    */
    'agentId'?: string;
    /**
    * The creation timestamp, in milliseconds
    */
    'createdAt'?: string;
    /**
    * Tell if the group is hidden on transactions main menu
    */
    'hidden'?: boolean;
    /**
    * The unique id that identifies the Group in the Book
    */
    'id'?: string;
    /**
    * The name of the Group
    */
    'name'?: string;
    /**
    * The name of the Group, lowercase, without spaces or special characters
    */
    'normalizedName'?: string;
    /**
    * The key/value custom properties of the Group
    */
    'properties'?: { [key: string]: string; };

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "agentId",
            "baseName": "agentId",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "string"
        },
        {
            "name": "hidden",
            "baseName": "hidden",
            "type": "boolean"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "normalizedName",
            "baseName": "normalizedName",
            "type": "string"
        },
        {
            "name": "properties",
            "baseName": "properties",
            "type": "{ [key: string]: string; }"
        }    ];

    static getAttributeTypeMap() {
        return Group.attributeTypeMap;
    }
}

