/**
 * app.bkper.com
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AccountBalances } from './accountBalances';
import { Balance } from './balance';

export class GroupBalances {
    'accountBalances'?: Array<AccountBalances>;
    'balances'?: Array<Balance>;
    'checkedCumulativeBalance'?: string;
    'checkedPeriodBalance'?: string;
    'credit'?: boolean;
    'cumulativeBalance'?: string;
    'name'?: string;
    'periodBalance'?: string;
    'permanent'?: boolean;
    'uncheckedCumulativeBalance'?: string;
    'uncheckedPeriodBalance'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "accountBalances",
            "baseName": "accountBalances",
            "type": "Array<AccountBalances>"
        },
        {
            "name": "balances",
            "baseName": "balances",
            "type": "Array<Balance>"
        },
        {
            "name": "checkedCumulativeBalance",
            "baseName": "checkedCumulativeBalance",
            "type": "string"
        },
        {
            "name": "checkedPeriodBalance",
            "baseName": "checkedPeriodBalance",
            "type": "string"
        },
        {
            "name": "credit",
            "baseName": "credit",
            "type": "boolean"
        },
        {
            "name": "cumulativeBalance",
            "baseName": "cumulativeBalance",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "periodBalance",
            "baseName": "periodBalance",
            "type": "string"
        },
        {
            "name": "permanent",
            "baseName": "permanent",
            "type": "boolean"
        },
        {
            "name": "uncheckedCumulativeBalance",
            "baseName": "uncheckedCumulativeBalance",
            "type": "string"
        },
        {
            "name": "uncheckedPeriodBalance",
            "baseName": "uncheckedPeriodBalance",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return GroupBalances.attributeTypeMap;
    }
}

