/**
 * app.bkper.com
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ModelFile {
    /**
    * The id of agent that created the resource
    */
    'agentId'?: string;
    /**
    * The file content Base64 encoded
    */
    'content'?: string;
    /**
    * The file content type
    */
    'contentType'?: string;
    /**
    * The creation timestamp, in milliseconds
    */
    'createdAt'?: string;
    /**
    * The unique id that identifies the file in the book
    */
    'id'?: string;
    /**
    * The file name
    */
    'name'?: string;
    /**
    * The file size in bytes
    */
    'size'?: number;
    /**
    * The file serving url
    */
    'url'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "agentId",
            "baseName": "agentId",
            "type": "string"
        },
        {
            "name": "content",
            "baseName": "content",
            "type": "string"
        },
        {
            "name": "contentType",
            "baseName": "contentType",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "size",
            "baseName": "size",
            "type": "number"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ModelFile.attributeTypeMap;
    }
}

