/**
 * app.bkper.com
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Account } from './account';

export class Transaction {
    /**
    * The id of agent that created the resource
    */
    'agentId'?: string;
    /**
    * The amount on format ####.##
    */
    'amount'?: string;
    /**
    * Tell if the transaction is a checked
    */
    'checked'?: boolean;
    /**
    * The creation timestamp, in milliseconds
    */
    'createdAt'?: string;
    'creditAccount'?: Account;
    /**
    * The date on ISO format yyyy-MM-dd
    */
    'date'?: string;
    /**
    * The date on format of the Book
    */
    'dateFormatted'?: string;
    /**
    * The date number representation on format YYYYMMDD
    */
    'dateValue'?: number;
    'debitAccount'?: Account;
    /**
    * The transaction description
    */
    'description'?: string;
    /**
    * The files attached to the transaction
    */
    'files'?: Array<any>;
    /**
    * The unique id that identifies the transaction in the book
    */
    'id'?: string;
    /**
    * Tell if the transaction is already posted on accounts, otherwise is a draft
    */
    'posted'?: boolean;
    /**
    * The key/value custom properties of the Transaction
    */
    'properties'?: { [key: string]: string; };
    /**
    * The transaction remote ids, to avoid duplication
    */
    'remoteIds'?: Array<string>;
    /**
    * The transaction #hashtags
    */
    'tags'?: Array<string>;
    /**
    * Tell if transaction is trashed
    */
    'trashed'?: boolean;
    /**
    * The transaction urls
    */
    'urls'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "agentId",
            "baseName": "agentId",
            "type": "string"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "string"
        },
        {
            "name": "checked",
            "baseName": "checked",
            "type": "boolean"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "string"
        },
        {
            "name": "creditAccount",
            "baseName": "creditAccount",
            "type": "Account"
        },
        {
            "name": "date",
            "baseName": "date",
            "type": "string"
        },
        {
            "name": "dateFormatted",
            "baseName": "dateFormatted",
            "type": "string"
        },
        {
            "name": "dateValue",
            "baseName": "dateValue",
            "type": "number"
        },
        {
            "name": "debitAccount",
            "baseName": "debitAccount",
            "type": "Account"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "files",
            "baseName": "files",
            "type": "Array<any>"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "posted",
            "baseName": "posted",
            "type": "boolean"
        },
        {
            "name": "properties",
            "baseName": "properties",
            "type": "{ [key: string]: string; }"
        },
        {
            "name": "remoteIds",
            "baseName": "remoteIds",
            "type": "Array<string>"
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "Array<string>"
        },
        {
            "name": "trashed",
            "baseName": "trashed",
            "type": "boolean"
        },
        {
            "name": "urls",
            "baseName": "urls",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return Transaction.attributeTypeMap;
    }
}

